// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOUzS1VLqTvOV9p1qlWY7pQuIXw40opo',
    appId: '1:568183265167:web:ae644f7a25d4d7d9a99dfa',
    messagingSenderId: '568183265167',
    projectId: 'sts-services-app',
    authDomain: 'sts-services-app.firebaseapp.com',
    storageBucket: 'sts-services-app.appspot.com',
    measurementId: 'G-H73XDPYJ1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClSnb_1ATdXbdnF886BsFX5wxagKOUeNM',
    appId: '1:568183265167:android:4156eff1bc0853d7a99dfa',
    messagingSenderId: '568183265167',
    projectId: 'sts-services-app',
    storageBucket: 'sts-services-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwXJ9g1jcOZX0TZfL8Kk39NaIMRDI6D0',
    appId: '1:568183265167:ios:923ed02c0a797ab6a99dfa',
    messagingSenderId: '568183265167',
    projectId: 'sts-services-app',
    storageBucket: 'sts-services-app.appspot.com',
    iosBundleId: 'com.example.urbanClapUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRwXJ9g1jcOZX0TZfL8Kk39NaIMRDI6D0',
    appId: '1:568183265167:ios:8a8807b1c10812a1a99dfa',
    messagingSenderId: '568183265167',
    projectId: 'sts-services-app',
    storageBucket: 'sts-services-app.appspot.com',
    iosBundleId: 'com.example.urbanClapUi.RunnerTests',
  );
}
